name: Test DAGs

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U scikit-learn
        python -m pip install -U pip setuptools wheel Cython
        pip install -U scikit-surprise
        pip install -r requirements.txt
        pip check
    - name: Lint with Flake8
      run: |
        pip install flake8
#        flake8 --ignore E501 dags --benchmark -v
    - name: Confirm Black code compliance (psf/black)
      run: |
        pip install pytest-black
#        pytest dags --black -v
    - name: Test with Pytest
      run: |
        pip install pytest
        cd test
        pytest dag_tests.py -v